src/Entity/Oeuvre.php
<?php

namespace App\Entity;

use App\Repository\OeuvreRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use App\Entity\Category;
use App\Entity\Parcours;

#[ORM\Entity(repositoryClass: OeuvreRepository::class)]
class Oeuvre
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $nom = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $description_o = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $artiste = null;

    #[ORM\Column(length: 255)]
    private ?string $coordonee_lat = null;

    #[ORM\Column(length: 255)]
    private ?string $coordonee_lon = null;

    #[ORM\Column(length: 255)]
    private ?string $photo = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $alt_img = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $adresse = null;

    #[ORM\ManyToOne(inversedBy: 'rela_cat')]
    private ?Category $rela_cat = null;

    #[ORM\ManyToOne(inversedBy: 'rela_oeuvre')]
    private ?Parcours $rela_oeuvre = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $credit = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getDescriptionO(): ?string
    {
        return $this->description_o;
    }

    public function setDescriptionO(?string $description_o): self
    {
        $this->description_o = $description_o;

        return $this;
    }

    public function getArtiste(): ?string
    {
        return $this->artiste;
    }

    public function setArtiste(?string $artiste): self
    {
        $this->artiste = $artiste;

        return $this;
    }

    public function getCoordoneeLat(): ?string
    {
        return $this->coordonee_lat;
    }

    public function setCoordoneeLat(string $coordonee_lat): self
    {
        $this->coordonee_lat = $coordonee_lat;

        return $this;
    }

    public function getCoordoneeLon(): ?string
    {
        return $this->coordonee_lon;
    }

    public function setCoordoneeLon(string $coordonee_lon): self
    {
        $this->coordonee_lon = $coordonee_lon;

        return $this;
    }

    public function getPhoto(): ?string
    {
        return $this->photo;
    }

    public function setPhoto(string $photo): self
    {
        $this->photo = $photo;

        return $this;
    }

    public function getAltImg(): ?string
    {
        return $this->alt_img;
    }

    public function setAltImg(?string $alt_img): self
    {
        $this->alt_img = $alt_img;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(?string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getRelaCat(): ?Category
    {
        return $this->rela_cat;
    }

    public function setRelaCat(?Category $rela_cat): self
    {
        $this->rela_cat = $rela_cat;

        return $this;
    }

    public function getRelaOeuvre(): ?Parcours
    {
        return $this->rela_oeuvre;
    }

    public function setRelaOeuvre(?Parcours $rela_oeuvre): self
    {
        $this->rela_oeuvre = $rela_oeuvre;

        return $this;
    }

    public function getCredit(): ?string
    {
        return $this->credit;
    }

    public function setCredit(?string $credit): self
    {
        $this->credit = $credit;

        return $this;
    }
}

src/Form/OeuvreType.php
<?php

namespace App\Form;

use App\Entity\Oeuvre;
use App\Repository\OeuvreRepository;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Validator\Constraints\Length;
use Symfony\Component\Validator\Constraints\NotBlank;


class OeuvreType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom', TextType::class, ['label' => 'Nom'])
            ->add('description_o')
            ->add('artiste')
            ->add('coordonee_lat')
            ->add('coordonee_lon')
            ->add('photo')
            ->add('alt_img')
            ->add('adresse')
            ->add('credit')
            // ->add('rela_cat', ChoiceType::class, []);
            // ->add('rela_oeuvre')
            ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Oeuvre::class,
        ]);
    }
}

src/Controller/OeuvreController.php
<?php

namespace App\Controller;

use App\Entity\Category;
use App\Entity\Oeuvre;
use App\Form\OeuvreType;
use App\Repository\OeuvreRepository;
use App\Repository\CategoryRepository;
use App\Repository\ParcoursRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/oeuvre')]
class OeuvreController extends AbstractController
{
    #[Route('/', name: 'app_oeuvre_index', methods: ['GET'])]
    public function index(OeuvreRepository $oeuvreRepository, CategoryRepository $categoryRepository, Request $request): Response
    {
        $category = $request->query->get('category');


        if ($category == 'all' || $category == NULL) {
            $oeuvres = $oeuvreRepository->findAllOeuvreCat();
        } else {
            $oeuvres = $this->getDoctrine()
                ->getRepository(Oeuvre::class)
                ->findAllOeuvreByIdCateg($category);
        }

        return $this->render('oeuvre/index.html.twig', [
            'oeuvres' => $oeuvres,
            'categories' => $categoryRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_oeuvre_new', methods: ['GET', 'POST'])]
    public function new(Request $request, OeuvreRepository $oeuvreRepository, CategoryRepository $categoryRepository, ParcoursRepository $parcoursRepository): Response
    {
        $oeuvre = new Oeuvre();
        $form = $this->createForm(OeuvreType::class, $oeuvre);
        $form->handleRequest($request);

        $category = $categoryRepository->findAll();
        $parcours = $parcoursRepository->findAll();

        if ($form->isSubmitted() && $form->isValid()) {

            if ($request->request->get('rela_cat')){
                $oeuvre->setRelaCat($categoryRepository->find($request->request->get('rela_cat')));
            }

            if ($request->request->get('rela_oeuvre')){
                $oeuvre->setRelaOeuvre($parcoursRepository->find($request->request->get('rela_oeuvre')));
            }

            $oeuvreRepository->save($oeuvre, true);

            return $this->redirectToRoute('app_oeuvre_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('oeuvre/new.html.twig', [
            'oeuvre' => $oeuvre,
            'form' => $form,
            'category' => $category,
            'parcour' => $parcours
        ]);
    }

    #[Route('/{id}', name: 'app_oeuvre_show', methods: ['GET'])]
    public function show(Oeuvre $oeuvre): Response
    {
        return $this->render('oeuvre/show.html.twig', [
            'oeuvre' => $oeuvre,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_oeuvre_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Oeuvre $oeuvre, CategoryRepository $categoryRepository, OeuvreRepository $oeuvreRepository, ParcoursRepository $parcoursRepository): Response
    {
        $form = $this->createForm(OeuvreType::class, $oeuvre);
        $form->handleRequest($request);

        // $categoryRepository->findAll(); permet de récupérer toutes les catégories en BDD 
        $category = $categoryRepository->findAll();
        $parcours = $parcoursRepository->findAll();

        if ($form->isSubmitted() && $form->isValid()) {

            // $oeuvre->setRelaCat();                   Permet d'insérer le nouvel object category
            // $categoryRepository->find(   (id)  )     Find récupère la catégorie grâce à son id 
            // $request->request->get('rela_cat')       Ceci permet de récupérer la valeur associé dans le formulaire avec le name 'rela_cat'

            if ($request->request->get('rela_cat')){
                $oeuvre->setRelaCat($categoryRepository->find($request->request->get('rela_cat')));
            }

            if ($request->request->get('rela_oeuvre')){
                $oeuvre->setRelaOeuvre($parcoursRepository->find($request->request->get('rela_oeuvre')));
            }
            
            $oeuvreRepository->save($oeuvre, true);

            return $this->redirectToRoute('app_oeuvre_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('oeuvre/edit.html.twig', [
            'oeuvre' => $oeuvre,
            'form' => $form,
            'category' => $category,
            'parcour' => $parcours
        ]);
    }

    #[Route('/{id}', name: 'app_oeuvre_delete', methods: ['POST'])]
    public function delete(Request $request, Oeuvre $oeuvre, OeuvreRepository $oeuvreRepository): Response
    {
        if ($this->isCsrfTokenValid('delete' . $oeuvre->getId(), $request->request->get('_token'))) {
            $oeuvreRepository->remove($oeuvre, true);
        }

        return $this->redirectToRoute('app_oeuvre_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/oeuvre/_delete_form.html.twig
<form method="post" action="{{ path('app_oeuvre_delete', {'id': oeuvre.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ oeuvre.id) }}">
    <button class="btn">Delete</button>
</form>

templates/oeuvre/_form.html.twig
{{ form_start(form) }}

{{ form_widget(form) }}

<label for="">Catégorie</label>
<select style="width: 5rem" name="rela_cat">
    {% for categories in category %}
        <option value="{{ categories.id }}" {% if oeuvre.relaCat and categories.id == oeuvre.relaCat.id %} selected {% endif %}>{{ categories.CatName }}</option>
    {% endfor %}
</select>

<label for="">Parcour</label>
<select style="width: 5rem" name="rela_oeuvre">
    {% for parcours in parcour %}
        <option value="{{ parcours.id }}" {% if oeuvre.RelaOeuvre and parcours.id == oeuvre.RelaOeuvre.id %} selected {% endif %}>{{ parcours.nom }}</option>
    {% endfor %}
</select>

<button class="btn">{{ button_label|default('Save') }}</button>

{{ form_end(form) }}

templates/oeuvre/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Oeuvre{% endblock %}

{% block main %}
    <h1>Edit Oeuvre</h1>

    {{ include('oeuvre/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_oeuvre_index') }}">back to list</a>

    {{ include('oeuvre/_delete_form.html.twig') }}
{% endblock %}

templates/oeuvre/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Les oeuvres{% endblock %}

{% block stylesheets %}
<link rel="stylesheet" href="{{ asset('css/oeuvres.css') }}">
<script type="text/javascript" src="{{ asset('js/oeuvres.js') }}" defer></script>
{% endblock %}

{% block titre %}
<h1>Les oeuvres</h1>
{% endblock %}

{% block main %}

    <!--<table class="table">
        <tbody>
        {% for oeuvre in oeuvres %}
            <tr>
                <td>{{ oeuvre.id }}</td>
                <td>{{ oeuvre.nom }}</td>
                <td>
                    <a href="{{ path('app_oeuvre_show', {'id': oeuvre.id}) }}">show</a>
                    <a href="{{ path('app_oeuvre_edit', {'id': oeuvre.id}) }}">edit</a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>-->
    {% if is_granted('ROLE_ADMIN') %}
        <a href="{{ path('app_oeuvre_new') }}">Create new</a>
    {% endif %}


<!-- VERSION 1.1 -->
<section class="desc">
    <p class="description">Venez découvrir les nombreuses œuvres de nos parcours. Ces Street Art ont été réalisé par des artistes passionnés et dévoués à un monde plus coloré, plus vivant. Plongez dans Strasbourg, à travers des peintures, des collages, des fresques, des graffitis... Ils ont dynamisé la vie dans cette capitale européenne. Apprenez à lever les yeux lors de vos balades quotidiennes et pénétrez dans un nouveau monde.</p>
    <div class="decouv">
        <h4>Découvrez nos parcours</h4>
        <a href="{{ path('app_parcours_index') }}"><i class="bi bi-arrow-right-circle"></i></a>
    </div>
</section>
<section>
    <form method="get" action="{{ path('app_oeuvre_index') }}" class="formb">
        <label for="category">Trier par :</label>
        <select name="category" id="category" class="buttonform">
            <option value="all">Toutes les catégories</option>
            {% for category in categories %}
            <option value="{{ category.id }}">{{ category.CatName }}</option>
            {% endfor %}
        </select>
        <button type="submit" class="buttonform btnfo">Filtrer</button>
    </form>

    <div class="container-card">
        {% for oeuvre in oeuvres %}
        <div class="baqueron">
            <div class="card">
                <img src="{{oeuvre.photo}}" alt="{{oeuvre.altImg}}">
                <div class="card-cont">
                    <h4>{{oeuvre.nom}}</h4>
                    <p>Par {{oeuvre.artiste}}</p>
                    <p class="cat">{{oeuvre.relaCat.CatName}}</p>
                    <a href="{{ path('app_oeuvre_show', {'id': oeuvre.id}) }}"><i class="bi bi-arrow-right-circle"></i></a>
                    
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</section>
{% endblock %}

templates/oeuvre/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Oeuvre{% endblock %}

{% block main %}
    <h1>Create new Oeuvre</h1>

    {{ include('oeuvre/_form.html.twig') }}

    <a href="{{ path('app_oeuvre_index') }}">back to list</a>
{% endblock %}

templates/oeuvre/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{oeuvre.nom}}{% endblock %}
{% block titre %}
<h1>{{oeuvre.nom}}</h1>
{% endblock %}

{% block stylesheets %}
<link rel="stylesheet" href="{{ asset('css/oeuvre.css') }}">
{% endblock %}

{% block main %}
<section class="oeuvre_spe">
    <div>
        <h2>{{ oeuvre.nom }}</h2>
        <h3>{{ oeuvre.artiste }}</h3>
        <figure class="graf">
            <img src="{{ oeuvre.photo }}" alt="{{oeuvre.altImg}}">
            <figcaption>© {{ oeuvre.credit }}</figcaption>
        </figure>

        <div class="desc">
            <p>{{ oeuvre.descriptionO }}</p>
        </div>


        <div class="adresse">
            <i class="bi bi-geo-alt-fill"></i>
            <p>{{oeuvre.adresse}}</p>
        </div>

            <div class="oeuvre_parc">
                <a href="{{ path('app_parcours_show', {'id': oeuvre.relaOeuvre.id}) }}"><p>Découvrez son parcours</p></a>
                <a href="{{ path('app_parcours_show', {'id': oeuvre.relaOeuvre.id}) }}"><i class="bi bi-arrow-right-circle"></i></a>
            </div>
    </div>


</section>
{% if is_granted('ROLE_ADMIN') %}
<a href="{{ path('app_oeuvre_index') }}">back to list</a>

<a href="{{ path('app_oeuvre_edit', {'id': oeuvre.id}) }}">edit</a>

{{ include('oeuvre/_delete_form.html.twig') }}
{% endif %}
{% endblock %}